name: Build and Push to Docker Hub

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ghost-drive-be:${{ steps.version.outputs.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/ghost-drive-be:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ghost-drive-be:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ghost-drive-be:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/ghost-drive-be
          short-description: "Ghost Drive Backend API - Self-hosted cloud storage solution"
          readme-filepath: ./README.md

      - name: Image digest
        run: echo "Image pushed successfully with tag ${{ steps.version.outputs.VERSION }}"

